default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: ENV['DB_NAME]
  username: ENV['DB_USERNAME]
  password: ENV['DB_PASSWORD']
  port: 5432
  pool: 5
  timeout: 5000


